"use client";

import type {
  GraphEdge,
  GraphNode,
  GraphNodeType,
  KnowledgeGraphData,
} from "@mitonexus/shared-types";

export type GraphViewMode = "patient" | "full";

export type PatientTargetSummary = Record<GraphNodeType, GraphNode[]>;

type GraphEdgeRef =
  | GraphEdge
  | (Omit<GraphEdge, "source" | "target"> & {
      source: string | { id?: string };
      target: string | { id?: string };
    });

export function getPatientTargetedNodeIds(nodes: GraphNode[], edges: GraphEdge[]): Set<string> {
  const nodeById = new Map(nodes.map((node) => [node.id, node]));
  const adjacency = buildAdjacency(edges);

  const abnormalMarkers = nodes.filter(
    (node) => node.type === "marker" && (node.abnormal || readStatus(node) !== "optimal"),
  );
  const affectedCascades = nodes.filter(
    (node) => node.type === "cascade" && (node.abnormal || readStatus(node) !== "optimal"),
  );
  const therapies = nodes.filter((node) => node.type === "therapy");

  const seedNodes = [...abnormalMarkers, ...affectedCascades, ...therapies];
  const targetedNodeIds = new Set<string>();

  for (const seedNode of seedNodes) {
    for (const nodeId of expandSeedNeighborhood(seedNode.id, nodeById, adjacency)) {
      targetedNodeIds.add(nodeId);
    }
  }

  return targetedNodeIds;
}

export function filterGraphToNodeIds(
  data: KnowledgeGraphData,
  nodeIds: Set<string>,
): KnowledgeGraphData {
  if (nodeIds.size === 0) {
    return data;
  }

  const filteredNodes = data.nodes.filter((node) => nodeIds.has(node.id));
  const filteredEdges = data.edges.filter((edge) => {
    const sourceId = readLinkedNodeId(edge.source);
    const targetId = readLinkedNodeId(edge.target);
    return Boolean(sourceId && targetId && nodeIds.has(sourceId) && nodeIds.has(targetId));
  });
  const filteredPositions = data.precomputed_positions
    ? Object.fromEntries(
        Object.entries(data.precomputed_positions).filter(([nodeId]) => nodeIds.has(nodeId)),
      )
    : null;

  return {
    ...data,
    nodes: filteredNodes,
    edges: filteredEdges,
    precomputed_positions: filteredPositions,
  };
}

export function buildPatientTargetSummary(
  nodes: GraphNode[],
  targetedNodeIds: Set<string>,
): PatientTargetSummary {
  const summary: PatientTargetSummary = {
    marker: [],
    gene: [],
    cascade: [],
    therapy: [],
    pathway: [],
  };

  for (const node of nodes) {
    if (!targetedNodeIds.has(node.id)) {
      continue;
    }
    summary[node.type].push(node);
  }

  for (const nodeType of Object.keys(summary) as GraphNodeType[]) {
    summary[nodeType].sort((left, right) => {
      if (left.abnormal !== right.abnormal) {
        return left.abnormal ? -1 : 1;
      }
      return right.centrality - left.centrality;
    });
  }

  return summary;
}

export function getPatientTargetReason(
  node: GraphNode,
  targetedNodeIds: Set<string>,
): string | null {
  if (!targetedNodeIds.has(node.id)) {
    return null;
  }

  switch (node.type) {
    case "marker":
      return node.abnormal
        ? "This blood marker is outside the patient's optimal range and was flagged by the algorithm as actionable."
        : "This blood marker was analyzed directly for the patient and retained as relevant context.";
    case "cascade":
      return "This signaling cascade was assessed as affected for the patient and is part of the active disease-pressure map.";
    case "therapy":
      return "This therapy is part of the patient-specific recommendation set generated by the reasoning workflow.";
    case "gene":
      return "This gene is connected to the patient's abnormal markers or affected cascades and remains in focus for interpretation.";
    case "pathway":
      return "This pathway is linked to the patient's abnormal markers, affected cascades, or prioritized therapy plan.";
  }
}

function buildAdjacency(edges: GraphEdgeRef[]): Map<string, GraphEdgeRef[]> {
  const adjacency = new Map<string, GraphEdgeRef[]>();
  for (const edge of edges) {
    const sourceId = readLinkedNodeId(edge.source);
    const targetId = readLinkedNodeId(edge.target);
    if (!sourceId || !targetId) {
      continue;
    }
    adjacency.set(sourceId, [...(adjacency.get(sourceId) ?? []), edge]);
    adjacency.set(targetId, [...(adjacency.get(targetId) ?? []), edge]);
  }
  return adjacency;
}

function collectNeighborsByType(
  sourceIds: Iterable<string>,
  adjacency: Map<string, GraphEdgeRef[]>,
  nodeById: Map<string, GraphNode>,
  allowedTypes: GraphNodeType[],
): Set<string> {
  const allowed = new Set(allowedTypes);
  const collected = new Set<string>();

  for (const sourceId of sourceIds) {
    for (const edge of adjacency.get(sourceId) ?? []) {
      const sourceNodeId = readLinkedNodeId(edge.source);
      const targetNodeId = readLinkedNodeId(edge.target);
      const neighborId = sourceNodeId === sourceId ? targetNodeId : sourceNodeId;
      if (!neighborId) {
        continue;
      }

      const neighbor = nodeById.get(neighborId);
      if (neighbor && allowed.has(neighbor.type)) {
        collected.add(neighborId);
      }
    }
  }

  return collected;
}

function expandSeedNeighborhood(
  seedNodeId: string,
  nodeById: Map<string, GraphNode>,
  adjacency: Map<string, GraphEdgeRef[]>,
): Set<string> {
  const seedNode = nodeById.get(seedNodeId);
  if (!seedNode) {
    return new Set<string>();
  }

  const includedNodeIds = new Set<string>([seedNodeId]);

  const addGroup = (nodeIds: Iterable<string>) => {
    for (const nodeId of nodeIds) {
      includedNodeIds.add(nodeId);
    }
  };

  switch (seedNode.type) {
    case "marker": {
      const genes = collectNeighborsByType([seedNodeId], adjacency, nodeById, ["gene"]);
      const directCascades = collectNeighborsByType([seedNodeId], adjacency, nodeById, ["cascade"]);
      const cascades = new Set<string>([
        ...directCascades,
        ...collectNeighborsByType(genes, adjacency, nodeById, ["cascade"]),
      ]);
      const therapies = collectNeighborsByType(cascades, adjacency, nodeById, ["therapy"]);
      const pathways = new Set<string>([
        ...collectNeighborsByType([seedNodeId], adjacency, nodeById, ["pathway"]),
        ...collectNeighborsByType(cascades, adjacency, nodeById, ["pathway"]),
      ]);

      addGroup(genes);
      addGroup(cascades);
      addGroup(therapies);
      addGroup(pathways);
      break;
    }
    case "gene": {
      const markers = collectNeighborsByType([seedNodeId], adjacency, nodeById, ["marker"]);
      const cascades = collectNeighborsByType([seedNodeId], adjacency, nodeById, ["cascade"]);
      const therapies = collectNeighborsByType(cascades, adjacency, nodeById, ["therapy"]);
      const pathways = new Set<string>([
        ...collectNeighborsByType(markers, adjacency, nodeById, ["pathway"]),
        ...collectNeighborsByType(cascades, adjacency, nodeById, ["pathway"]),
      ]);

      addGroup(markers);
      addGroup(cascades);
      addGroup(therapies);
      addGroup(pathways);
      break;
    }
    case "cascade": {
      addGroup(collectNeighborsByType([seedNodeId], adjacency, nodeById, ["marker"]));
      addGroup(collectNeighborsByType([seedNodeId], adjacency, nodeById, ["gene"]));
      addGroup(collectNeighborsByType([seedNodeId], adjacency, nodeById, ["therapy"]));
      addGroup(collectNeighborsByType([seedNodeId], adjacency, nodeById, ["pathway"]));
      break;
    }
    case "therapy": {
      const cascades = collectNeighborsByType([seedNodeId], adjacency, nodeById, ["cascade"]);
      const markers = collectNeighborsByType(cascades, adjacency, nodeById, ["marker"]);
      const genes = collectNeighborsByType(cascades, adjacency, nodeById, ["gene"]);
      const pathways = collectNeighborsByType(cascades, adjacency, nodeById, ["pathway"]);

      addGroup(cascades);
      addGroup(markers);
      addGroup(genes);
      addGroup(pathways);
      break;
    }
    case "pathway": {
      const cascades = collectNeighborsByType([seedNodeId], adjacency, nodeById, ["cascade"]);
      const markers = collectNeighborsByType([seedNodeId], adjacency, nodeById, ["marker"]);
      const genes = new Set<string>([
        ...collectNeighborsByType(cascades, adjacency, nodeById, ["gene"]),
        ...collectNeighborsByType(markers, adjacency, nodeById, ["gene"]),
      ]);
      const therapies = collectNeighborsByType(cascades, adjacency, nodeById, ["therapy"]);

      addGroup(cascades);
      addGroup(markers);
      addGroup(genes);
      addGroup(therapies);
      break;
    }
  }

  return includedNodeIds;
}

function readStatus(node: GraphNode): string | null {
  const status = node.metadata.status;
  return typeof status === "string" ? status : null;
}

function readLinkedNodeId(value: string | { id?: string }): string | null {
  if (typeof value === "string") {
    return value;
  }
  if (typeof value?.id === "string") {
    return value.id;
  }
  return null;
}
